### ISSUE TITLE
[Design] Homework storage

### ISSUE THREAD

**Issue by Ungerfall** [Ungerfall/ekids-chatbot#6]

**Comment by braidsencurls** [comment]
Attached are the following:
1. ERD for the homework storage 
2. OpenAPI documentation for homework management 

[ekids homework storage.zip](https://github.com/Ungerfall/ekids-chatbot/files/12800581/ekids.homework.storage.zip)

**Comment by Ungerfall** [comment]
Can you please write ERD here using [mermaid](https://mermaid.js.org/syntax/entityRelationshipDiagram.html) 
The github markdown can render mermaid diagrams, for example
```mermaid
---
title: Order example
---
erDiagram
    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ LINE-ITEM : contains
    CUSTOMER }|..|{ DELIVERY-ADDRESS : uses
```

**Comment by braidsencurls** [comment]
Updated it. Reference it as well in the README.md

Editor Link: https://www.mermaidchart.com/app/projects/9d4fd38b-1164-4768-9c7e-3a6bd1f20f96/diagrams/3b1b3640-9139-4565-93a6-9b9b31c44e39/version/v0.1/edit

SVG Link: https://www.mermaidchart.com/raw/3b1b3640-9139-4565-93a6-9b9b31c44e39?theme=light&version=v0.1&format=svg

**Comment by Ungerfall** [comment]
> Updated it. Reference it as well in the README.md
> 
> Editor Link: https://www.mermaidchart.com/app/projects/9d4fd38b-1164-4768-9c7e-3a6bd1f20f96/diagrams/3b1b3640-9139-4565-93a6-9b9b31c44e39/version/v0.1/edit
> 
> SVG Link: https://www.mermaidchart.com/raw/3b1b3640-9139-4565-93a6-9b9b31c44e39?theme=light&version=v0.1&format=svg

The links are not working anymore. Do you have access to the diagrams? Actually, you can paste the diagram code here and it will be rendered properly
